branches:
  only:
    - master
    - dev
before_install:
- npm install -g ionic@3.9.2 cordova@7.0.1
script: 
- npm install
- ionic cordova build browser
deploy:
  provider: script
  skip_cleanup: true
  script: deploy/travis-push.sh
  on:
    branch: dev
